[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; ---- 16 MB Flash + 8 MB PSRAM (N16R8) ----
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB

build_flags =
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_ESP32S3_EYE
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    esp32-camera
    madhephaestus/ESP32Servo@^3.0.5